baseurl = "http://shubhconsulting.in/"
publishdir = "public"
languageCode = "en-us"
title = "Shubh Consulting - Maximize Your Potential"
canonifyurls = false
googleAnalytics = ""

[markup]
    defaultMarkdownHandler = "blackfriday"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Shubh Consulting"
    description = "Astrology, Vastu and Numerology Services"

    # The path must be relative to the static folder
    favicon = "favicon.png"


    # Navigation
    [params.navigation]
        brand = "Shubh Consulting"

        [params.navigation.links]
            intro     = "Intro"
            astro     = "Astrology"
            vastu     = "Vastu"
            numro     = "Numerology"
            acharya   = "Consultant"
            contact   = "Contact"
            recentposts   = "Recent"

    [[menu.main]]
        name = "F.A.Q."
        identifier = "faq"
        url = "http://shubhconsulting.in/faq/"

    # Hero section
    [params.hero]
        # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
        slogan     = "Shubh Consulting"
        subtitle   = "Astrology, Vastu and Numerology Services"

		# Intro section
    [params.intro]
        headline = "Introduction"
        text   = "Shubh Consulting helps you transform life through the knowledge of Astrology, Vastu and Numerology. We help you optimize your potential, transform your challenges into opportunities, and lead a prosperous and holistic life.<br/><br/>When you consult us, you will come to know the exact Astrological, Vastu and Numerological reasons for the problems that you face in your life and how you can overcome them with very simple and effective solutions."

    # Aside section
		# Consultants section
    [params.acharya]
        headline = "Consultant"

    [params.acharya.astro]
        title = "**Krupa Sinroja Dalal**"
        img = "acharya.jpg"
        text = "Shubh Consulting is a venture of *Krupa Sinroja Dalal*, started with an intention to provide very simple and yet effective solutions to life challenges, through the ancient vedic wisdom of India. She has been studying astrology from a very young age and inherited the interests of occult sciences from her father, who taught her the basics of Astrology and Vastu-shastra at a very young age.<br/><br/>While having a successful career in the banking industry, she realised that no matter what career, class, or creed one belongs to, destiny always has its way and the stars make their presence felt in one’s life. After having a lot of success with cases within the circle of family, friends, and colleagues, she started to help people within the community and guided them to a better life with Astrology, Vastu, Numerology and Signature Analysis.<br/><br/>With an experience of more than 25 years, she is respected for her deep knowledge of the subject of Astrology, Vastu, and Numerology. She has an easy-to-work-with attitude and has provided simple and yet, customised solutions to many individuals - whether professionals, business owners or industrialists. She also teaches these sciences in individual one-to-one sessions."


		# Astro section
    [params.astro]
        headline = "Astrology"
        title = "The Influence of Celestial Bodies"
        text  = "Jyothish is an ancient traditional Hindu system of astrology, and is one of the most time-tested and oldest systems in the world. The Sanskrit word ‘Jyotish’ (ja-yo-teesh) means ‘science of light.’ In the western world, it is also called Vedic astrology.<br/><br/>At Shubh Consulting, we provide you with effective astrological solutions, and remedies which help you overcome obstacles in life with ease and achieve your life goals. Through your Life Analysis, we help you:<ul><li>Understand your horoscope, understanding of who you really are, helping you know your strengths and weaknesses and understand the skill and abilities that you brought with you into this lifetime.</li><li>Imparts you an understanding of the cycles of your own life; your favorable and unfavorable years, and the astrological recommendations to overcome the difficult periods of life through meaningful and yet, simple solutions.</li><li>Provide you guidance on when to begin a project, a new enterprise, a new home or relocation.</li><li>And guide you in matters of education, on the choice of careers, profession and other important aspects of life decisions.</li></ul>"

		# Vastu section
    [params.vastu]
        headline = "Vastu"
        title = "The Antient Art of Architecture"
        text   = "Vastu shastra is an ancient science that explains how the laws of nature affect human dwellings and states the rules for building a home that would ensure peace, prosperity and health of its residents. Its theories are based on the five elements — Water, Air, Fire, Earth and Space — and their effects on human life.  <br/><br/>  Vishwakarma Prakash, an ancient book of Vastu Shastra, lays down the basic rules of vastu and emphasizes on the importance of different vastu zones in a building. It asserts the fact that residents who perform activities in a household based on vastu rules, lead a life filled with peace and prosperity. It explains the significance of different vastu zones of a house and the corresponding aspects of life that they govern. Following is an overview of the significance of major vastu zones in a house: <ul> <li>North: Domintaes the career and money aspects of your life. An ideal place for a living room. Nice to have green plants here.</li> <li>North-East: Dominates the spiritual and psychological aspects of your life. The direction is ideal for mediation and Pooja based activities. Avoid having bedroom, toilets or a septic tank here. Keep your temple here.</li> <li>East: Dominates your social life. Bedrooms, living rooms and study tables can be placed here. Its also good to have a garden here.</li> <li>South-East: An ideal zone for a kitchen. Avoid water based activities here. This zone governs your zeal and enthusiasm for life.</li> <li>South: Dominates your fame and status in the society. Can be used as a bedroom. Head should be kept towards the south while sleeping. You may display your medals and awards here.</li> <li>South-West: Dominates your family life. Ideal for a master bedroom. You can place family photographs placed here to improve harmony in your family.</li> <li>West: Dominates the Creative, Educational and Gain aspects of your life. Can be used as a bedroom or a living room. You may have your dining here too. You may display your artworks here. It is nice to have metal sculptures here.</li> <li>North-West: An ideal zone for storage. Can also be used as a living room or a bedroom.</li> </ul> Vastu Sashtra also asserts that performing activities in a wrong zone of the house can have adverse affects on the residents, also called Vastu Dosh. These wrongly placed activities such as placement of toilets and stairs affect peace of mind, and hamper growth and prosperity of the residents. If you can relocate these activities to favorable zones, then you should do so. If you are unable to relocate these activities, there are ways to overcome their ill effects without structural demolition within the house.<br/><br/> At Shubh Consulting, we provide simple and effective solutions without structural demolitions. We recommend use of metal wires and strips, tools such as pyramids and yantras, and color, sound and form energy, to help an individual realize his potential to the fullest and lead a life of peace and prosperity."

		# Numro section
    [params.numro]
        headline = "Numerology"
        title = "The Occult Significance of Numbers"
        text   = "Numerology is the study of the symbolism of numbers. It is used to determine a person’s personality, strengths and talents, obstacles, inner needs, emotional wellbeing, and compatibility with others. Whether you use numerology to examine your life, take advantage of unexplored opportunities, confirm your talents or simply figure out where to go next, numerology can be a penetrating tool that helps you understand your own self and your loved ones better. Numerology presents a complete picture, revealing all the diverse parts of your personality and how they come together to create the person you are. With this complete view, you will be able to make the most of your strengths and also identify areas of weakness that you need to strengthen.  <br/><br/> Numerology is a branch of the divine science — Vedic astrology. Numerology deals with only nine basic numbers, from 1 to 9, each of which has its own significance. Given your date of birth, is it possible to calculate all important events from your your past, present and even the future. You can determine the personality or the character based on your birth number. You can even find out your lucky numbers, lucky days, lucky colors or lucky stones too!  <br/><br/> This is how Numerology works. Everything in the universe vibrates at its own frequency. By finding the vibration rate of any object, you can establish the qualities and energies associated with it. By applying the principles of numerology — and using only a name and birth date as the basic data — you can determine the dominating frequency of an individual. A numerological analysis of the calculated frequencies provides significant information on personality and character.  <br/><br/> At the core, all numbers are reduced to the single digits 1 through 9 except the special master numbers 11 and 22. 1 through 9, 11 and 22 represent the major vibration rates associated with people’s characteristics. The numbers are reduced by addition. The number 15, for instance, is reduced by adding 1 + 5 to get 6. Similarly, the number 1974 can be reduced by adding 1 + 9 + 7 + 4 to get 21. The 21 can be further reduced by adding 2 + 1 to get 3. Letters in individuals’ names are converted to numbers and then added together. These numbers, in turn, are also reduced until you get one of the basic numbers.  <br/><br/> At Shubh Consulting, we find out your favorable and unfavorable numbers, and guide you in attaining their maximum benefit."

		# Recent posts section
    [params.recentposts]
        headline = "Checkout the Recent Blog Posts"

    # Contact section
    [params.contact]
        headline = "Get In Touch!"
        description = ""

        [[params.contact.list]]
            icon = "fa-facebook-official"
            text = "[Shubh Consulting](https://www.facebook.com/ShubhConsulting-112730963848261/)"

        [[params.contact.list]]
            icon = "fa-envelope"
            text = "info@shubhconsulting.in"

        [[params.contact.list]]
            icon = "fa-phone"
            text = "+91-9825600347"
