baseurl = "http://swarodaya.github.io/shubh"
publishdir = "public"
languageCode = "en-us"
title = "Shubh Consulting - Helping You Maximize Your Potential"
canonifyurls = false
googleAnalytics = ""

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Shubh Consulting"
    description = "Helping You Maximize Your Potential"

    # The path must be relative to the static folder
    favicon = "favicon.png"


    # Navigation
    [params.navigation]
        brand = "Shubh Consulting"

        [params.navigation.links]
            intro     = "Intro"
            benefits  = "Benefits"
            price     = "Price"
            #testimonials  = "Testimonials"
            astro     = "Astrology"
            vastu     = "Vastu"
            numro     = "Numerology"
            acharya   = "Acharya"
            contact   = "Contact"
            recentposts   = "Recent"

    [[menu.main]]
        name = "Blog"
        identifier = "blog"
        url = "/blog/"

    # Hero section
    [params.hero]
        # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
        slogan     = "Shubh Consulting<br/>Helping You Maximize Your Potential"
        subtitle   = "&quot;We should insert a quote here.&quot;<br/>-&nbsp;Tapan Karecha."

		# Intro section
    [params.intro]
        headline = "Introduction"
        text   = "Shubh consulting helps you transform life through the knowledge of Astrology, Numerology and Vastu. We help you optimize your potential, transform your challenges into opportunities, and your aspirations and dreams into reality.<br/><br/>When you consult us, you will come to know the exact Astrological, Numerological and Vastu reasons for the problems that you face in your life."

    # Benefits section
    [params.benefits]
        headline = "Benefits"

        [[params.benefits.list]]
            icon = "fa-home"
            title = "Personal"
            text = "<b>Vastu Report:</b><br/>We study the floor plan and interior design of your residence, and then recommend non-destructive changes in order to help you realize your goals and aspirations, and also help you resolve your life challenges and problems. A vastu compliant home helps you enjoy these benefits: <ul> <li>New career opportunities and growth.</li> <li>Improved finances.</li> <li>Better relations with family, friends, and colleagues.</li> <li>Help your children learn better and perform at the best of their abilities.</li> <li>Reduced mental stress.</li> <li>Enhanced clarity of thought and peace of mind.</li> <li>Get rid of inner fears and anxieties.</li> <li>Lead a healthy and happy life.</li> </ul> <b>Astrology report:</b> <ul> <li>Your horoscope.</li> <li>Understanding what makes you who you are. The strengths and weakness of your birth-chart. Knowing the skill and abilities that you brought with you into this lifetime.</li> <li>Understanding the cycles of your life.Your favorable and unfavorable years. Astrological recommendations to over the difficult periods of life through Gem-stones and other solutions.</li> <li>Determining when to begin a project, a new enterprise or relocation.</li> <li>Guidance in matters of education, on the choice of careers, profession and other important aspects of life.</li> </ul> <b>Numerology report:</b> <ul> <li>The significance of your Birth Day Number. Discover your strengths, challenges, life lessons, and potential.</li> <li>Your favorable and unfavorable numbers. Your favorable and unfavorable days and colors. How to use this information while making important decisions in life as well as in day-to-day activities.</li> <li>Recommendations to changes in your name to achieve maximum prosperity and happiness. Recommendations to your brand and company”s name to enhance your fortunes.</li> <li>Recommendations to make your signature powerful and effective.</li> <ul>"

        [[params.benefits.list]]
            icon = "fa-university"
            title = "Professional"
            text = "We consult businesses to help them: <ul> <li>Maximize profits and turnover.</li> <li>Improved working relationships with partners, staff and clients.</li> <li>Ensure smooth functioning of day-to-day affairs.</li> <li>Quality control and check.</li> <li>Ensuring on-time delivery of goods and services.</li> <li>Hiring of reliable and trust worthy staff.</li> <li>Clearing of consignments and completion of deals on time.</li> <li>Smooth dealing with government agencies and getting approvals.</li> <li>Procuring more orders and sales.</li> </ul> Consultation includes: <ul> <li><b>Astrology</b>: The astrological compatibly of the individuals involved in the business. Suitable remedies to overcome challenges in horoscope.</li> <li><b>Numerology</b>: The numerological compatibility of the individuals involved in the venture. Suitable suggestions to overcome problems posed by them, including study of the business name.</li> <li><b>Vastu</b>: Recommendations will be provided in matters of:</li> </ul> <ul> <li>Logo, Name, Banner and Visiting Card review and recommendations for improvement based on astrological and vaastu principles.</li> <li>Shapes and colors to be used at the entrance and exit doors.</li> <li>Shapes and colors to be used while designing the space.</li> <li>Placement of heavy and light machinery.</li> <li>Placement of computers, telephones and fax machines.</li> <li>Display, storage and dispatch of goods.</li> <li>Placement of important files and documents.</li> <li>Placement of cash registers and lockers.</li> <li>Sitting position for the business owners.</li> <li>Sitting position for managers of each department and their staff.</li> <li>Conference and meeting rooms.</li> <li>Reception desk and waiting areas for customers.</li> <li>Proper placement of drinking water coolers, pantry and canteens.</li> <li>Customized Solutions will be provided as per the nature and the needs of the business.</li> </ul>"

    # Feature modals
    [params.testimonials.modal]
        buttonText = "Close"

    [params.testimonials]
        headline = "Testimonials"
        description = "Click on image for details"

    # Features section
		# Note: The pictures must all be jpg of size 1000 x 1000 pixels
    [[params.testimonials.list]]
        modalID = 1
        title = "Mr. Bob Hill,<br/>Accomplished Musician, Atlantis<hr/>&quot;I stopped making music, but now I can sing again.&quot;"
        img = "xyz.jpg"
        description = "Accomplished Musician, Atlantis"

    # Aside section
    [params.course]
        headline = "Pricing for Consultation"
        text = "---"
				listheadline = "Course Schedule"

        [[params.course.list]]
            title = "**Day 1**<br/>_Nadis_"
            text = "<ul> <li>Introduction to the Swar Yog.</li> <li>Understanding, usage, and activation of the three Nadis (Ida, Pingala, and Susuhmana).</li> <li>Nadi meditation.</li> </ul>"


        [[params.course.list]]
            title = "**Day 2**<br/>_Tatwas_"
            text = "<ul> <li>Introduction to the five Tatwas (space, air, fire, water, and earth).</li> <li>Understanding, usage, and activation of the five Tatwas.</li> <li>Tatwa meditation.</li> </ul>"


        [[params.course.list]]
            title = "**Day 3**<br/>_Practicals_"
            text = "<ul> <li>Introduction and usage of the Swar Saptang.</li> <li>Introduction and usage of the Swar log.</li> <li>Tatwa experience in the real world (site visit).</li> </ul>"

        [[params.course.list]]
            title = "**Day 4**<br/>_Advanced_"
            text = "<ul> <li>Tatwa sthapana (advance meditation).</li> <li>Forty Five Devtas of the Vastu Purush Mandal.</li> <li>Questions and Answers.</li> <li>Graduation.</li> </ul>"

		# Acharya section
    [params.acharya]
        headline = "Krupa Maharaj"
        title = "Batch of Sept, 2016<br/>Goa"
        img = "acharya.jpg"
        text   = "Krup Maharaj is a Jyotish Practitioner.<br/><br/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi dictum eros id libero consectetur, in finibus dui venenatis. Nulla commodo feugiat odio quis ornare. Phasellus rhoncus libero ut viverra interdum. Praesent ornare sagittis vehicula. Proin tristique, purus id blandit venenatis, justo lectus condimentum ante, et viverra urna lorem non est. Suspendisse potenti. Aenean in suscipit mauris, dictum molestie nibh."

		# Astro section
    [params.astro]
        headline = "Astrology"
        title = "The Influence of Celestial Bodies"
        text   = "Jyothish is an ancient traditional Hindu system of astrology, and is one of the most time-tested and oldest systems in the world. The Sanskrit word ‘Jyotish’ (ja-yo-teesh) means ‘science of light.’ In the western world, it is also called Vedic astrology. The origins of Vedic astrology are in the Vedas — the ancient scriptures of Hindus. Vedic astrology is the science of understanding the influence of heavenly bodies on our life. The science of light is not the visible light, but light that enlightens the inner self; which minimizes uncertainty; which allows us to plan our future, to improve our odds in our favor and to reduce the risk of failure.  <br/><br/> When practiced correctly, Vedic astrology is an excellent tool within Sanatan Dharm and can help avoid pitfalls and take remedial action to achieve a smoother, balanced life, as we strive for material and spiritual progress.  <br/><br/> Sanatan Dharm promotes harmony, encourages us to seek resonance with our surroundings, and teaches us that alignment between the individual and the forces of the universe is desirable. Through tools such as vastu, ayurved, numerology and jyotish, we align our vibrations with those of the universe for a happy, productive and an ideal life; and we seek perfection.  <br/><br/> Spirituality is the basis of Vedic astrology and it is designed to reveal the inner person. Changing the inner person can also change his/her outer life. By studying the planets and their relationships, we can determine their influences on our well being, and consequently chart a path towards prosperity, health, happiness, and the ultimate goal — moksh.  <br/><br/> Vedic astrology is unique in that it offers simple solutions to compensate for the influences of celestial bodies. Therapies include mantras, meditation, rituals, gems, and spiritual suggestions. Therefore like vastu and ayurved, Vedic astrology offers solutions to people so they can gain control over their life.  <br/><br/> The astrologer uses Vedic astrology to chart the horoscope of an individual. It is said that a horoscope in your hands is a map of your destiny. The secrets contained in the horoscope can only be revealed by a Vedic astrologer. The birth-chart, or horoscope, is a symbolic representation of the Earth, planets, and stars at the time of one’s birth. It is a divine language, a mystic code by which God has communicated a person’s destiny, knowing which, a wise person will exercise his free will to optimize the result.  <br/><br/> At Shubh Consulting, we provide you with effective astrological solutions, and our remedies include use of gem stones and mantras which help you overcome obstacles in life with ease and achieve your goals in life."

		# Vastu section
    [params.vastu]
        headline = "Vastu"
        title = "The Antient Art of Architecture"
        text   = "Vastu shastra is an ancient science that explains how the laws of nature affect human dwellings and states the rules for building a home that would ensure peace, prosperity and health of its residents. Its theories are based on the five elements — Water, Air, Fire, Earth and Space — and their effects on human life.  <br/><br/>  Vishwakarma Prakash, an ancient book of Vastu Shastra, lays down the basic rules of vastu and emphasizes on the importance of different vastu zones in a building. It asserts the fact that residents who perform activities in a household based on vastu rules, lead a life filled with peace and prosperity. It explains the significance of different vastu zones of a house and the corresponding aspects of life that they govern. Following is an overview of the significance of major vastu zones in a house: <ul> <li>North: Domintaes the career and money aspects of your life. An ideal place for a living room. Nice to have green plants here.</li> <li>North-East: Dominates the spiritual and psychological aspects of your life. The direction is ideal for mediation and Pooja based activities. Avoid having bedroom, toilets or a septic tank here. Keep your temple here.</li> <li>East: Dominates your social life. Bedrooms, living rooms and study tables can be placed here. Its also good to have a garden here.</li> <li>South-East: An ideal zone for a kitchen. Avoid water based activities here. This zone governs your zeal and enthusiasm for life.</li> <li>South: Dominates your fame and status in the society. Can be used as a bedroom. Head should be kept towards the south while sleeping. You may display your medals and awards here.</li> <li>South-West: Dominates your family life. Ideal for a master bedroom. You can place family photographs placed here to improve harmony in your family.</li> <li>West: Dominates the Creative, Educational and Gain aspects of your life. Can be used as a bedroom or a living room. You may have your dining here too. You may display your artworks here. It is nice to have metal sculptures here.</li> <li>North-West: An ideal zone for storage. Can also be used as a living room or a bedroom.</li> </ul> Vastu Sashtra also asserts that performing activities in a wrong zone of the house can have adverse affects on the residents, also called Vastu Dosh. These wrongly placed activities such as placement of toilets and stairs affect peace of mind, and hamper growth and prosperity of the residents. If you can relocate these activities to favorable zones, then you should do so. If you are unable to relocate these activities, there are ways to overcome their ill effects without structural demolition within the house.<br/><br/> At Shubh Consulting, we provide simple and effective solutions without structural demolitions. We recommend use of metal wires and strips, tools such as pyramids and yantras, and color, sound and form energy, to help an individual realize his potential to the fullest and lead a life of peace and prosperity."

		# Numro section
    [params.numro]
        headline = "Numerology"
        title = "The Occult Significance of Numbers"
        text   = "Numerology is the study of the symbolism of numbers. It is used to determine a person’s personality, strengths and talents, obstacles, inner needs, emotional wellbeing, and compatibility with others. Whether you use numerology to examine your life, take advantage of unexplored opportunities, confirm your talents or simply figure out where to go next, numerology can be a penetrating tool that helps you understand your own self and your loved ones better. Numerology presents a complete picture, revealing all the diverse parts of your personality and how they come together to create the person you are. With this complete view, you will be able to make the most of your strengths and also identify areas of weakness that you need to strengthen.  <br/><br/> Numerology is a branch of the divine science — Vedic astrology. Numerology deals with only nine basic numbers, from 1 to 9, each of which has its own significance. Given your date of birth, is it possible to calculate all important events from your your past, present and even the future. You can determine the personality or the character based on your birth number. You can even find out your lucky numbers, lucky days, lucky colors or lucky stones too!  <br/><br/> This is how Numerology works. Everything in the universe vibrates at its own frequency. By finding the vibration rate of any object, you can establish the qualities and energies associated with it. By applying the principles of numerology — and using only a name and birth date as the basic data — you can determine the dominating frequency of an individual. A numerological analysis of the calculated frequencies provides significant information on personality and character.  <br/><br/> At the core, all numbers are reduced to the single digits 1 through 9 except the special master numbers 11 and 22. 1 through 9, 11 and 22 represent the major vibration rates associated with people’s characteristics. The numbers are reduced by addition. The number 15, for instance, is reduced by adding 1 + 5 to get 6. Similarly, the number 1974 can be reduced by adding 1 + 9 + 7 + 4 to get 21. The 21 can be further reduced by adding 2 + 1 to get 3. Letters in individuals’ names are converted to numbers and then added together. These numbers, in turn, are also reduced until you get one of the basic numbers.  <br/><br/> At Shubh Consulting, we find out your favorable and unfavorable numbers, and guide you in attaining their maximum benefit."

		# Recent posts section
    [params.recentposts]
        headline = "Checkout the Recent Blog Posts"

    # Contact section
    [params.contact]
        headline = "Get In Touch!"
        description = ""

        [[params.contact.list]]
            icon = "fa-envelope"
            text = "[info@shubhconsulting.in](mailto:info@shubhconsulting.in?subject=General Inquiry)"

        [[params.contact.list]]
            icon = "fa-facebook"
            text = "[https://www.facebook.com/shubhconsulting/](https://www.facebook.com/shubhconsulting/)"

        [[params.contact.list]]
            icon = "fa-phone"
            text = "+91-9876-543210"
