baseurl = "https://shubhconsulting.in/"
publishdir = "public"
languageCode = "en-us"
title = "Shubh Consulting - Maximize Your Potential"
canonifyurls = false
googleAnalytics = ""

[markup]
    defaultMarkdownHandler = "blackfriday"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Shubh Consulting"
    description = "Astrology, Vastu and Numerology Services"

    # The path must be relative to the static folder
    favicon = "favicon.png"


    # Navigation
    [params.navigation]
        brand = "Shubh Consulting"

        [params.navigation.links]
            intro     = "Intro"
            astro     = "Astro"
            vastu     = "Vastu"
            numro     = "Numero"
            contact   = "Contact"
            recentposts   = "Recent"

    [[menu.main]]
        name = "Testimonials"
        identifier = "testimonials"
        url = "/testimonials/"

    # Hero section
    [params.hero]
        # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
        slogan     = "Shubh Consulting"
        subtitle   = "Astrology, Vastu and Numerology Services"

		# Intro section
    [params.intro]
        headline = "Introduction"
        text   = "Shubh Consulting, a wing of swarodaya.com, provides specialised solutions to life challenges, through the ancient vedic wisdom of Astrology, Vastu Shatra and Numerology.<br/><br/>Shubh Consulting is headed by Krupa Sinroja Dalal, who has been studying the ancient vedic sciences from a very young age and has inherited these interests from her father, who taught her the basics at a very young age! With time, she refined her knowledge under many other renowned gurus who helped her master her subjects.<br/><br/>While having a successful career in the banking industry, she realised that no matter what career, class, or creed one belongs to, destiny always has its way and presents challenges in life, which can be effectively resolved through the ancient vedic wisdom. After having a lot of successful cases, within the circle of family, friends, and colleagues, she started to help people professionally with Astrology, Vastu, Numerology and Signature Analysis.<br/><br/>With an experience of more than 25 years, she is highly respected for her deep knowledge, easy-to-work-with attitude and simple and yet, customised solutions to many individuals - be it professionals, business owners or industrialists.<br/><br/>She also teaches these sciences in individual one-to-one sessions."

		# Astro section
    [params.astro]
        headline = "Astrology"
        title = "The Influence of Celestial Bodies"
        text  = "Jyothish is an ancient traditional Hindu system of astrology, and is one of the most time-tested and oldest systems in the world. The Sanskrit word ‘Jyotish’ (ja-yo-teesh) means ‘science of light.’ In the western world, it is also known as Vedic astrology.<br/><br/>At Shubh Consulting, we provide you with effective astrological solutions, and remedies which help you overcome obstacles in life with ease and achieve your life goals. Through your Astro Life Analysis, we help you:<ul><li>The strengths and weaknesses of your horoscope.</li><li>The favourable and unfavourable cycles of your life.</li><li>Guidance on matters of personal and professional life.</li><li>Guidance on matters of work and relationships.</li><li>Guidance on matters of education, relocation, and other life decisions.</li></ul>"

		# Vastu section
    [params.vastu]
        headline = "Vastu"
        title = "The Ancient Science of Architecture"
        text  = "Vastu shastra is an ancient vedic indian science, that explains laws of nature in context of a built structure, and their impact on human life. A vastu compliant space (whether it is a home or an office) ensures peace, prosperity and health of its occupants. Wrongly placed activities such as placement of toilets and stairs disturb the peace of mind, and hamper growth.<br/><br/>Shubh Consulting aims at harmonizing life, by studying the floor plan of the space and suggesting easy and do-able vastu changes to it, to overcome the ill-effects caused by wrongly placed objects, colors and activities, without doing any kind of structural demolition. Shubh Consulting offers online consultation to clients within India and abroad.<br/><br/>At Shubh Consulting, we will guide you to make minor changes in your home in a way that, that you get:<ul><li>New career opportunities and growth.</li><li>Improved finances.</li><li>Better relations with family, friends, and colleagues.</li><li>Help your children learn better and perform at the best of their abilities.</li><li>Reduced mental stress.</li><li>Enhanced clarity of thought and peace of mind.</li><li>Get rid of inner fears and anxieties.</li><li>Lead a healthy and happy life</li></ul>"

		# Numro section
    [params.numro]
        headline = "Numerology and Signature Analysis"
        title = "The Occult Science of Numbers and Signs"
        text   = "Numerology is the study of the symbolism of numbers. It is used to determine a person’s personality, strengths and talents, obstacles, inner needs, emotional wellbeing, and compatibility with others. Whether you use numerology to examine your life, take advantage of unexplored opportunities, confirm your talents or simply figure out where to go next, numerology can be a penetrating tool that helps you understand your own self and your loved ones better. Numerology presents a complete picture, revealing all the diverse parts of your personality and how they come together to create the person you are.<br/><br/>Through your Numero-Signature report, we help you:<ul><li>Significance of your birth number.</li><li>Your strengths, challenges and potential.</li><li>Guidance on how to make important decisions in life.</li><li>Guidance on how to use this information in day-to-day activities.</li><li>Recommendations to make your signature powerful and effective.</li></ul>"

		# Recent posts section
    [params.recentposts]
        headline = "Checkout the Recent Blog Posts"

    # Contact section
    [params.contact]
        headline = "Get In Touch!"
        description = ""

        [[params.contact.list]]
            icon = "fa-envelope"
            text = "[info@shubhconsulting.in](mailto:info@shubhconsulting.com)"

        [[params.contact.list]]
            icon = "fa-phone"
            text = "+91-9825600347"

	[params.testimonials]
		headline = "Testimonials"
		description = "Click on image for details"

	[[params.testimonials.list]]
		modalID = 1
		title = "Ajay Batra"
		img = "ajay_batra.png"

	[[params.testimonials.list]]
		modalID = 2
		title = "Aman Gupta"
		img = "aman.png"

	[[params.testimonials.list]]
		modalID = 3
		title = "Chirag Panchal"
		img = "chirag_panchal.png"

	[[params.testimonials.list]]
		modalID = 4
		title = "Ddevya Sharma"
		img = "ddevya_sharma.png"

	[[params.testimonials.list]]
		modalID = 5
		title = "Dr. Archa"
		img = "dr_archa.png"

	[[params.testimonials.list]]
		modalID = 6
		title = "Hina Modashia"
		img = "hina_modashia.png"

	[[params.testimonials.list]]
		modalID = 7
		title = "Jaideep Sippy"
		img = "jaideep_sippy.png"

	[[params.testimonials.list]]
		modalID = 8
		title = "Kinnari Mankotia"
		img = "kinnari_mankotia.png"

	[[params.testimonials.list]]
		modalID = 9
		title = "Rutvi Sonawala"
		img = "rutvi_sonawala.png"

	[[params.testimonials.list]]
		modalID = 10
		title = "Shiva Kumar"
		img = "shiva_kumar.png"

	[[params.testimonials.list]]
		modalID = 11
		title = "Uma Aggarwal"
		img = "uma_aggarwal.png"

	[[params.testimonials.list]]
		modalID = 12
		title = "Umesh Sharma"
		img = "umesh_sharma.png"

